In [2]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

In [1]:
print("hello world") # roh je suis trop fort !

hello world


In [2]:
name = input("entrer nom: ")
print("hello", name)

hello nicolas


In [3]:
x = 1
print(x)

1


In [1]:
for i in range(0,21,2): #for de 0 à 20 par pas de 2
    print(i)

0
2
4
6
8
10
12
14
16
18
20


In [ ]:
i = 0
while i < 10: # while de  0 à 9
    print(i)
    i += 1

In [20]:

tb3D = np.array([[[1,2,3],[4,5,6],[7,8,9]], [[19,20,21],[22,23,24],[25,26,27]]]) # 2 tableaux 3D de 2 lignes et 3 colonnes 
print(tb3D) 
print(tb3D.ndim) # .ndim = nombre de dimensions / ici 3

[[[ 1  2  3]
  [ 4  5  6]
  [ 7  8  9]]

 [[19 20 21]
  [22 23 24]
  [25 26 27]]]
3


In [18]:
print(tb3D[0, 2, 1]) # on prend le 2eme tableau, la 3eme ligne et la 2eme colonne / ici 8

8


In [14]:
maListe = [['pomme', 'rouge'], ['banane', 'jaune'], ['orange', 'orange'], ['poire', 'vert'], ['fraise', 'rouge']]
monDataFrame = pd.DataFrame(maListe , columns = ['fruit', 'couleur']) # Création d'un DataFrame à partir d'une liste de listes et avec des noms de colonnes
monDataFrame

fruit couleur
0   pomme   rouge
1  banane   jaune
2  orange  orange
3   poire    vert
4  fraise   rouge

In [8]:
myList = np.array([[0,1], [2,3], [4,5]])
myDataFrame = pd.DataFrame(myList, columns = ['even', 'odd'])
myDataFrame

even  odd
0     0    1
1     2    3
2     4    5
3     6    7
4     8    9

In [9]:
MonDictionnaire = {'fruit': ['pomme', 'banane', 'orange', 'poire', 'fraise'], 'couleur': ['rouge', 'jaune', 'orange', 'vert', 'rouge']}
myDataFrame = pd.DataFrame(MonDictionnaire)
myDataFrame

fruit couleur
0   pomme   rouge
1  banane   jaune
2  orange  orange
3   poire    vert
4  fraise   rouge

In [195]:
df = pd.read_csv('myFile0.csv', sep=',') # on lit le fichier csv avec comme séparateur le " , "
df.iloc[70:80] # on affiche les lignes 70 à 80. on aurai pu mettre df.head(10) pour afficher les 10 premières lignes ou df.tail(10) pour les 10 dernières

id   firstname  lastname                          email   
70  570       Randa   Minetta      Randa.Minetta@yopmail.com  \
71  571    Mathilda    Ammann    Mathilda.Ammann@yopmail.com   
72  572  Clementine      Love    Clementine.Love@yopmail.com   
73  573    Beverley  Wolfgram  Beverley.Wolfgram@yopmail.com   
74  574  Anestassia    Aldric  Anestassia.Aldric@yopmail.com   
75  575      Livvyy    Barrus      Livvyy.Barrus@yopmail.com   
76  576        Alex  Lunsford      Alex.Lunsford@yopmail.com   
77  577       Fanny    Jotham       Fanny.Jotham@yopmail.com   
78  578      Angela   Kinnard     Angela.Kinnard@yopmail.com   
79  579    Demetris     Zeeba     Demetris.Zeeba@yopmail.com   

                         email2      profession  
70      Randa.Minetta@gmail.com     firefighter  
71    Mathilda.Ammann@gmail.com          doctor  
72    Clementine.Love@gmail.com  police officer  
73  Beverley.Wolfgram@gmail.com          doctor  
74  Anestassia.Aldric@gmail.com  police officer  
75      Livvyy.Barrus@gmail.com       developer  
76      Alex.Lunsford@gmail.com       developer  
77       Fanny.Jotham@gmail.com     firefighter  
78     Angela.Kinnard@gmail.com          doctor  
79     Demetris.Zeeba@gmail.com          doctor

In [72]:
df = pd.read_csv('myFile0.csv')
df.set_index('firstname', inplace = True) # on change l'index du DataFrame en le mettant sur la colonne firstname au lieu de 0,1,2,3,4.. et inplace = True pour que la modification soit permanente
df

id    lastname                         email   
firstname                                                   
Abbie       500        Alva        Abbie.Alva@yopmail.com  \
Mamie       501     Gombach     Mamie.Gombach@yopmail.com   
Gwyneth     502       Abbot     Gwyneth.Abbot@yopmail.com   
Jennica     503     Kamaria   Jennica.Kamaria@yopmail.com   
Johna       504  Anastatius  Johna.Anastatius@yopmail.com   
...         ...         ...                           ...   
Madalyn    1495        Bebe      Madalyn.Bebe@yopmail.com   
Brianna    1496      Mendez    Brianna.Mendez@yopmail.com   
Rubie      1497       Wenda       Rubie.Wenda@yopmail.com   
Jaclyn     1498      Kimmie     Jaclyn.Kimmie@yopmail.com   
Cyb        1499      Peonir        Cyb.Peonir@yopmail.com   

                               email2   profession  
firstname                                           
Abbie            Abbie.Alva@gmail.com       worker  
Mamie         Mamie.Gombach@gmail.com  firefighter  
Gwyneth       Gwyneth.Abbot@gmail.com  firefighter  
Jennica     Jennica.Kamaria@gmail.com       worker  
Johna      Johna.Anastatius@gmail.com       worker  
...                               ...          ...  
Madalyn        Madalyn.Bebe@gmail.com    developer  
Brianna      Brianna.Mendez@gmail.com       doctor  
Rubie           Rubie.Wenda@gmail.com       doctor  
Jaclyn        Jaclyn.Kimmie@gmail.com       doctor  
Cyb              Cyb.Peonir@gmail.com       doctor  

[1000 rows x 5 columns]

In [66]:
df.head(10) # on affiche les 10 premières lignes du DataFrame
df.tail(10) # on affiche les 10 dernières lignes du DataFrame

In [77]:
df2 = pd.read_csv('myFile2.csv')
df2.describe() # on affiche les statistiques du DataFrame

id          int        float
count  1000.000000  1000.000000  1000.000000
mean    599.500000   511.534000   485.699297
std     288.819436   291.373447   286.032586
min     100.000000     1.000000     2.332000
25%     349.750000   258.750000   231.692250
50%     599.500000   514.000000   487.902500
75%     849.250000   752.000000   722.146750
max    1099.000000  1000.000000  1000.239000

In [82]:
df2.iloc[2:5] # on affuche les lignes 2 à 5 du DataFrame mais .iloc[] est une meilleure pratique que df2[2:5]

id  int    float        date                         email2   
2  102   85  496.195  1916-08-13  undefined.undefined@gmail.com  \
3  103  429  117.456  1957-03-04  undefined.undefined@gmail.com   
4  104  949  695.489  1935-09-21  undefined.undefined@gmail.com   

       profession code  
2  police officer   IM  
3       developer   BN  
4          worker   SV

In [90]:
df2[['int', 'date', 'email2']] # on affiche les colonnes int, date et email2 du DataFrame

int        date                         email2
0    290  2012-05-02  undefined.undefined@gmail.com
1    227  1953-10-05  undefined.undefined@gmail.com
2     85  1916-08-13  undefined.undefined@gmail.com
3    429  1957-03-04  undefined.undefined@gmail.com
4    949  1935-09-21  undefined.undefined@gmail.com
..   ...         ...                            ...
995  173  1902-05-25  undefined.undefined@gmail.com
996   99  1924-05-09  undefined.undefined@gmail.com
997  256  1998-11-13  undefined.undefined@gmail.com
998  208  2009-12-02  undefined.undefined@gmail.com
999  346  2009-03-08  undefined.undefined@gmail.com

[1000 rows x 3 columns]

In [137]:
thirdRow = [True if i == 500 else False for i in range(len(df2))] # on crée une liste de booléens avec True si i == 500 sinon False
#len() = longueur de la liste si 1000 éléments len() = 1000 
df2[thirdRow]

id  int   float        date                         email2 profession   
500  600  214  90.726  1967-10-15  undefined.undefined@gmail.com     worker  \

    code  
500   BR

In [136]:
condition = df2['int'] > 990 # on crée une liste de booléens avec True si la valeur de la colonne int est supérieur à 900 sinon False
df2[condition]

id   int    float        date                         email2   
29   129   997  475.794  2016-12-14  undefined.undefined@gmail.com  \
78   178   996  205.398  1941-05-04  undefined.undefined@gmail.com   
110  210   996  839.591  1920-12-21  undefined.undefined@gmail.com   
255  355   998  305.071  1946-04-27  undefined.undefined@gmail.com   
310  410   999  254.798  1925-05-23  undefined.undefined@gmail.com   
479  579   997  541.513  1959-03-15  undefined.undefined@gmail.com   
578  678   994  101.701  2010-09-24  undefined.undefined@gmail.com   
588  688   993  562.848  1987-05-13  undefined.undefined@gmail.com   
593  693   995  284.519  2007-10-29  undefined.undefined@gmail.com   
649  749   999  295.611  1934-05-05  undefined.undefined@gmail.com   
748  848   996  124.738  2016-09-01  undefined.undefined@gmail.com   
759  859  1000  313.087  1909-05-04  undefined.undefined@gmail.com   

         profession code  
29        developer   CX  
78           worker   NE  
110  police officer   GY  
255       developer   HN  
310     firefighter   HU  
479       developer   US  
578     firefighter   SH  
588  police officer   SV  
593       developer   MG  
649     firefighter   EC  
748       developer   GS  
759          worker   FO

In [150]:
df2[(df2['float'] > 500) & (df2['int'] > 990)] # on affiche les lignes du DataFrame où la valeur de la colonne float est supérieur à 500 et la valeur de la colonne int est supérieur à 990


id  int    float        date                         email2   
110  210  996  839.591  1920-12-21  undefined.undefined@gmail.com  \
479  579  997  541.513  1959-03-15  undefined.undefined@gmail.com   
588  688  993  562.848  1987-05-13  undefined.undefined@gmail.com   

         profession code  
110  police officer   GY  
479       developer   US  
588  police officer   SV

In [160]:
df2[(df2['float'] > 994) | (df2['int'] > 990)] # on affiche les lignes du DataFrame où la valeur de la colonne float est supérieur à 994 ou la valeur de la colonne int est supérieur à 990

id   int     float        date                         email2   
29   129   997   475.794  2016-12-14  undefined.undefined@gmail.com  \
78   178   996   205.398  1941-05-04  undefined.undefined@gmail.com   
110  210   996   839.591  1920-12-21  undefined.undefined@gmail.com   
255  355   998   305.071  1946-04-27  undefined.undefined@gmail.com   
310  410   999   254.798  1925-05-23  undefined.undefined@gmail.com   
313  413   120   999.746  1961-04-28  undefined.undefined@gmail.com   
437  537   841  1000.239  1912-07-04  undefined.undefined@gmail.com   
449  549   157   995.456  1946-12-28  undefined.undefined@gmail.com   
479  579   997   541.513  1959-03-15  undefined.undefined@gmail.com   
578  678   994   101.701  2010-09-24  undefined.undefined@gmail.com   
588  688   993   562.848  1987-05-13  undefined.undefined@gmail.com   
593  693   995   284.519  2007-10-29  undefined.undefined@gmail.com   
649  749   999   295.611  1934-05-05  undefined.undefined@gmail.com   
717  817   298   996.399  1985-02-01  undefined.undefined@gmail.com   
748  848   996   124.738  2016-09-01  undefined.undefined@gmail.com   
759  859  1000   313.087  1909-05-04  undefined.undefined@gmail.com   

         profession code  
29        developer   CX  
78           worker   NE  
110  police officer   GY  
255       developer   HN  
310     firefighter   HU  
313       developer   AI  
437          doctor   IR  
449  police officer   BE  
479       developer   US  
578     firefighter   SH  
588  police officer   SV  
593       developer   MG  
649     firefighter   EC  
717       developer   HM  
748       developer   GS  
759          worker   FO

In [167]:
df2.loc[3,'int'] # on affiche la valeur de la ligne 0 et de la colonne int 429 ici

429

In [169]:
df2.loc[[3,5,7],['int','float']] # on affiche les valeurs des lignes 3,5 et 7 et des colonnes int et float

int    float
3  429  117.456
5  638  415.688
7   24  879.482

In [170]:
df2.loc[0:4,'int':'email2'] # on affiche les valeurs des lignes 0 à 4 et des colonnes int à email2

int    float        date                         email2
0  290  922.479  2012-05-02  undefined.undefined@gmail.com
1  227   83.986  1953-10-05  undefined.undefined@gmail.com
2   85  496.195  1916-08-13  undefined.undefined@gmail.com
3  429  117.456  1957-03-04  undefined.undefined@gmail.com
4  949  695.489  1935-09-21  undefined.undefined@gmail.com

In [173]:
df2.loc[6] = [256, 562, 25.65 , '2020-01-01', 'sdsds@sdsd.com', 'dev' ,' FR'] # on modifie la ligne 6 du DataFrame
df2.loc[6]

id                       256
int                      562
float                  25.65
date              2020-01-01
email2        sdsds@sdsd.com
profession               dev
code                      FR
Name: 6, dtype: object

In [177]:
df2.drop(6, inplace = True) # on supprime la ligne 6 du DataFrame
df2.iloc[3:7]

id  int    float        date                         email2 profession   
3  103  429  117.456  1957-03-04  undefined.undefined@gmail.com  developer  \
4  104  949  695.489  1935-09-21  undefined.undefined@gmail.com     worker   
5  105  638  415.688  1920-10-30  undefined.undefined@gmail.com     worker   
7  107   24  879.482  1977-04-25  undefined.undefined@gmail.com     doctor   

  code  
3   BN  
4   SV  
5   PL  
7   GH

In [ ]:
df2.drop ('my new column', axis = 1, inplace = True) # on supprime la colonne my new column du DataFrame, axis = 1 pour supprimer une colonne et axis = 0 pour supprimer une ligne
df2

In [186]:
df2.sort_values(by = 'int', ascending = False, inplace = True) # on trie le DataFrame par ordre décroissant de la colonne int
df2

id   int    float        date                         email2   
759   859  1000  313.087  1909-05-04  undefined.undefined@gmail.com  \
310   410   999  254.798  1925-05-23  undefined.undefined@gmail.com   
649   749   999  295.611  1934-05-05  undefined.undefined@gmail.com   
255   355   998  305.071  1946-04-27  undefined.undefined@gmail.com   
479   579   997  541.513  1959-03-15  undefined.undefined@gmail.com   
..    ...   ...      ...         ...                            ...   
8     108     4  302.783  1954-10-02  undefined.undefined@gmail.com   
766   866     4  244.897  1983-05-25  undefined.undefined@gmail.com   
905  1005     2  481.667  1995-03-19  undefined.undefined@gmail.com   
179   279     2  834.157  2009-01-01  undefined.undefined@gmail.com   
652   752     1  945.372  1972-01-07  undefined.undefined@gmail.com   

         profession code  
759          worker   FO  
310     firefighter   HU  
649     firefighter   EC  
255       developer   HN  
479       developer   US  
..              ...  ...  
8            doctor   SR  
766     firefighter   MD  
905  police officer   VI  
179  police officer   LS  
652  police officer   SD  

[999 rows x 7 columns]

In [189]:
df2.to_csv('myFile3add.csv', index_label = False , sep = ';') # on enregistre le DataFrame dans un fichier csv avec comme séparateur le " ; " et index_label = False pour ne pas avoir la colonne 0,1,2,3,4.. et sep = ';' pour avoir comme séparateur le " ; "