In [13]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

In [1]:
print("hello world") # roh je suis trop fort !

hello world


In [2]:
name = input("entrer nom: ")
print("hello", name)

hello nicolas


In [3]:
x = 1
print(x)

1


In [1]:
for i in range(0,21,2): #for de 0 à 20 par pas de 2
    print(i)

0
2
4
6
8
10
12
14
16
18
20


In [ ]:
i = 0
while i < 10: # while de  0 à 9
    print(i)
    i += 1

In [20]:

tb3D = np.array([[[1,2,3],[4,5,6],[7,8,9]], [[19,20,21],[22,23,24],[25,26,27]]]) # 2 tableaux 3D de 2 lignes et 3 colonnes 
print(tb3D) 
print(tb3D.ndim) # .ndim = nombre de dimensions / ici 3

[[[ 1  2  3]
  [ 4  5  6]
  [ 7  8  9]]

 [[19 20 21]
  [22 23 24]
  [25 26 27]]]
3


In [18]:
print(tb3D[0, 2, 1]) # on prend le 2eme tableau, la 3eme ligne et la 2eme colonne / ici 8

8


In [14]:
maListe = [['pomme', 'rouge'], ['banane', 'jaune'], ['orange', 'orange'], ['poire', 'vert'], ['fraise', 'rouge']]
monDataFrame = pd.DataFrame(maListe , columns = ['fruit', 'couleur']) # Création d'un DataFrame à partir d'une liste de listes et avec des noms de colonnes
monDataFrame

fruit couleur
0   pomme   rouge
1  banane   jaune
2  orange  orange
3   poire    vert
4  fraise   rouge